[build.environment]
  GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES = "true"
  NETLIFY_USE_YARN = "true"
  NODE_VERSION = "15"

[build]
  command = "build:with-storybook"
  publish = "public/"
  functions = "functions/handlers"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

