[build.environment]
  NODE_VERSION = "15"
  NETLIFY_USE_YARN = "true"

[build]
  command = "yarn netlify:build"
  publish = "public/"
  functions = "functions/handlers"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

