# Do not add configurations that will
# break either Gatsby builds or Storybook builds

# Set the publish directory and plugins in Netlify UI,
# adding them here will break the storybook builds

[build.environment]
  GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES = "true"
  GATSBY_GOOGLE_ANALYTICS_ID = "0"
  NETLIFY_USE_YARN = "true"
  NODE_VERSION = "15"

[build]
  command = "yarn build:with_storybook"
  publish = "public/"
  functions = "functions/handlers"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
