---
# --- Header ---

- type: AdminHeaderTopNavItem
  fields:
    label: String
    url: String

- type: AdminHeaderMainNavChild
  fields:
    label: String
    url: String

- type: AdminHeaderMainNavItem
  fields:
    button: Boolean
    children: "[AdminHeaderMainNavChild]"
    label: String
    url: String

- type: AdminHeader
  node: true
  fields:
    top_nav: "[AdminHeaderTopNavItem]"
    main_nav: "[AdminHeaderMainNavItem]"

# --- Footer ---

- type: AdminFooterPolicyLink
  fields:
    label: String
    url: String

- type: AdminFooterSocialLink
  fields:
    icon: String
    url: String

- type: AdminFooterMenuItem
  fields:
    label: String
    url: String

- type: AdminFooterMenu
  fields:
    heading: String
    links: "[AdminFooterMenuItem]"

- type: AdminFooter
  node: true
  fields:
    menus: "[AdminFooterMenu]"
    social_links: "[AdminFooterSocialLink]"
    policy_links: "[AdminFooterPolicyLink]"
    copyright: String

# --- SEO ---

- type: SeoMetaOg
  fields:
    description: String
    image: File
    title: String

- type: SeoMetaTwitter
  fields:
    card: String
    description: String
    image: File
    title: String

- type: SeoMeta
  fields:
    description: String
    image: File
    og: SeoMetaOg
    title: String
    twitter: SeoMetaTwitter

# --- Containers & Shared ---

- type: BlockConfig
  fields:
    margin_bottom: String
    text_align: String
    width: String

- type: Block
  fields:
    template: String
    body: String
    blocks: "[Block]"
    config: BlockConfig
    form:
      type: map
      name: Form
    image: File
    label: String
    src: String
    title: String
    url: String

# --- Page Layouts ---

- type: BasicPage
  fields:
    heading: String
    body: String

- type: FlexiblePage
  fields:
    blocks: "[Block]"

# --- Page ---

- type: Page
  node: true
  fields:
    exclude_from_sitemap: Boolean
    layout: String
    published: Boolean
    seo: SeoMeta
    title: String
    layout_basic: BasicPage
    layout_flexible: FlexiblePage

# --- Form ---

- type: FormField
  fields:
    label: String
    name: String
    required: Boolean
    select_appearance: String
    select_options: "[String]"
    solo: Boolean
    text_appearance: String
    text_placeholder: String
    text_validation: String
    title: String
    type: String
    width: String

- type: FormFieldGroup
  fields:
    heading: String
    fields: "[FormField]"

- type: Form
  node: true
  fields:
    title: String
    driver: String
    button_label: String
    field_groups: "[FormFieldGroup]"
