export default {
  default: {
    title: "Contact Form",
    model: "Form",
    button_label: "Submit",
    field_groups: [
      {
        title: "Personal Info",
        heading: "Personal Info",
        fields: [
          {
            title: "Name",
            type: "text",
            required: true,
            width: "half",
            select_options: [],
            label: "First Name",
            name: "name",
            text_appearance: "short",
            text_validation: "",
            text_placeholder: "",
            select_appearance: "",
            solo: true,
            appearance: "short",
            placeholder: "",
            validation: ""
          },
          {
            title: "Email",
            type: "text",
            label: "Email",
            required: true,
            width: "half",
            select_options: [],
            name: "email",
            text_appearance: "short",
            text_validation: "email",
            text_placeholder: "",
            select_appearance: "",
            solo: false,
            appearance: "short",
            placeholder: "",
            validation: "email"
          },
          {
            title: "Phone",
            type: "text",
            label: "Phone",
            required: true,
            width: "half",
            select_options: [],
            name: "phone",
            text_appearance: "short",
            text_validation: "phone",
            text_placeholder: "(xxx) xxx-xxxx",
            select_appearance: "",
            solo: false,
            appearance: "short",
            placeholder: "(xxx) xxx-xxxx",
            validation: "phone"
          },
          {
            title: "Gender",
            name: "gender",
            type: "select",
            required: true,
            width: "full",
            select_options: ["Female", "Male"],
            text_appearance: "",
            text_validation: "",
            text_placeholder: "",
            select_appearance: "radio",
            solo: false,
            appearance: "radio",
            label: "Gender",
            options: ["Female", "Male"]
          }
        ]
      },
      {
        title: "Address",
        heading: "Address",
        fields: [
          {
            title: "Street Address",
            type: "text",
            label: "Street Address",
            required: false,
            width: "half",
            select_options: [],
            name: "street_address",
            text_appearance: "short",
            text_validation: "",
            text_placeholder: "",
            select_appearance: "",
            solo: false,
            appearance: "short",
            placeholder: "",
            validation: ""
          },
          {
            title: "Suite / Apt.",
            name: "suite_apt",
            type: "text",
            required: false,
            width: "half",
            select_options: [],
            text_appearance: "short",
            text_validation: "",
            text_placeholder: "",
            select_appearance: "",
            solo: false,
            appearance: "short",
            label: "Suite / Apt.",
            placeholder: "",
            validation: ""
          },
          {
            title: "City",
            name: "city",
            type: "text",
            required: false,
            width: "half",
            select_options: [],
            text_appearance: "short",
            text_validation: "",
            text_placeholder: "",
            select_appearance: "",
            solo: false,
            appearance: "short",
            label: "City",
            placeholder: "",
            validation: ""
          },
          {
            title: "State",
            name: "state",
            type: "select",
            required: false,
            width: "quarter",
            select_options: [
              "Alabama",
              "Alaska",
              "Arizona",
              "Arkansas",
              "California",
              "Colorado",
              "Connecticut",
              "Delaware",
              "District Of Columbia",
              "Florida",
              "Georgia",
              "Hawaii",
              "Idaho",
              "Illinois",
              "Indiana",
              "Iowa",
              "Kansas",
              "Kentucky",
              "Louisiana",
              "Maine",
              "Maryland",
              "Massachusetts",
              "Michigan",
              "Minnesota",
              "Mississippi",
              "Missouri",
              "Montana",
              "Nebraska",
              "Nevada",
              "New Hampshire",
              "New Jersey",
              "New Mexico",
              "New York",
              "North Carolina",
              "North Dakota",
              "Ohio",
              "Oklahoma",
              "Oregon",
              "Pennsylvania",
              "Rhode Island",
              "South Carolina",
              "South Dakota",
              "Tennessee",
              "Texas",
              "Utah",
              "Vermont",
              "Virginia",
              "Washington",
              "West Virginia",
              "Wisconsin",
              "Wyoming"
            ],
            text_appearance: "",
            text_validation: "",
            text_placeholder: "",
            select_appearance: "dropdown",
            solo: false,
            appearance: "dropdown",
            label: "State",
            options: [
              "Alabama",
              "Alaska",
              "Arizona",
              "Arkansas",
              "California",
              "Colorado",
              "Connecticut",
              "Delaware",
              "District Of Columbia",
              "Florida",
              "Georgia",
              "Hawaii",
              "Idaho",
              "Illinois",
              "Indiana",
              "Iowa",
              "Kansas",
              "Kentucky",
              "Louisiana",
              "Maine",
              "Maryland",
              "Massachusetts",
              "Michigan",
              "Minnesota",
              "Mississippi",
              "Missouri",
              "Montana",
              "Nebraska",
              "Nevada",
              "New Hampshire",
              "New Jersey",
              "New Mexico",
              "New York",
              "North Carolina",
              "North Dakota",
              "Ohio",
              "Oklahoma",
              "Oregon",
              "Pennsylvania",
              "Rhode Island",
              "South Carolina",
              "South Dakota",
              "Tennessee",
              "Texas",
              "Utah",
              "Vermont",
              "Virginia",
              "Washington",
              "West Virginia",
              "Wisconsin",
              "Wyoming"
            ]
          },
          {
            title: "Zip Code",
            name: "zip",
            type: "text",
            required: false,
            width: "quarter",
            select_options: [],
            text_appearance: "short",
            text_validation: "",
            text_placeholder: "",
            select_appearance: "",
            solo: false,
            appearance: "short",
            label: "Zip Code",
            placeholder: "",
            validation: ""
          }
        ]
      },
      {
        title: "Message",
        heading: "Message",
        fields: [
          {
            title: "Message",
            type: "text",
            label: "Message",
            required: true,
            width: "full",
            select_options: [],
            name: "message",
            text_appearance: "long",
            text_validation: "",
            text_placeholder: "",
            select_appearance: "",
            solo: false,
            appearance: "long",
            placeholder: "",
            validation: ""
          }
        ]
      }
    ]
  }
}
