---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/content/pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - template-page
- type: directory
  path: src/content/forms
  label: Forms
  create: documents
  match: "**/*"
  templates:
  - model-form
- type: directory
  path: src/content/redirects
  label: Redirects
  create: documents
  match: "**/*"
  templates:
  - model-redirect
- type: directory
  path: src/content/admin
  label: Config
  create: none
  match: "**/*"
  templates:
  - admin-references
  - admin-seo
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
